spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:///apps/los/

server:
  port: 9196

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost    