server:
  port: 9196

spring:
  application:
    name: config-server
  profiles:
    active: native              # Use local files for configuration
  cloud:
    config:
      server:
        native:
          search-locations: file:///F:/Microservice/ # Path to configuration files

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server URL
  instance:
    prefer-ip-address: true      # Use IP address in registration

management:
  endpoints:
    web:
      exposure:
        include: "*"
