server:
  port: 9196

spring:
  application:
    name: config-server

  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: file:///F:/Microservice/

eureka:
  client:
    registry-fetch-interval-seconds: 10
  instance:
    ip-address: true
    lease-renewal-interval-in-seconds: 10



