spring:
  application:
    name: order-service  # Name of the Spring Boot application, identifying it as the order-service application

  profiles:
    active: native  # Specifies that the 'native' profile is active, indicating local file-based configuration

  cloud:
    config:
      discovery:
        enabled: true  # Enables service discovery for fetching the configuration from the config server via Eureka
        service-id: config-server  # Specifies the service ID of the config server in Eureka registry

      name: order-service,db  # The names of services for which the configuration is being retrieved (order-service and db in this case)
      fail-fast: true  # Ensures the application fails quickly if the configuration cannot be retrieved from the config server
      retry:
        initial-interval: 3000  # The initial interval (in milliseconds) between retry attempts when fetching configuration
        multiplier: 1.3  # Multiplier for increasing the retry interval after each failed attempt
        max-interval: 20000  # Maximum retry interval (in milliseconds)
        max-attempts: 20  # The maximum number of retry attempts when fetching configuration

  config:
    import: "optional:configserver:"  # Allows the application to import configuration from the config server (optional fallback)

server:
  port: 9192  # Specifies the port on which the order service will run (port 9192)

eureka:
  instance:
    prefer-ip-address: true  # Configures Eureka to register the instance using its IP address instead of its hostname
  client:
    service-url:
      default-zone: http://localhost:8761/eureka  # Specifies the URL of the Eureka server where this service will register
