spring:
  application:
    name: order-service
  cloud:
    discovery:
      enabled: true             # Enable discovery of Config Server via Eureka
      service-id: config-server # Service ID of the Config Server in Eureka

  config:
      import: "optional:configserver:" # Import configuration from Config Server

server:
  port: 9192                    # Order Service port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server URL
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
