spring:
  application:
    name: order-service
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: order-service,db
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 20000
        max-attempts: 20
  config:
    import: "optional:configserver:"

server:
  port: 9192

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

