spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: gateway-service
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 20000
        max-attempts: 20
  config:
    import: "optional:configserver:"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8989

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    jms:
      enabled: false

