spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # Enable dynamic routing based on Eureka services
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"  # Allow all origins
            allowedHeaders: "*"  # Allow all headers
            allowedMethods:      # Allow HTTP methods
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
  config:
    import: "optional:configserver:" # Import configuration from Config Server

server:
  port: 8989                     # Gateway port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server URL
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
